CREATE TABLE UserMasters (
    Id BIGINT PRIMARY KEY IDENTITY(1,1),
    FullName NVARCHAR(255) NOT NULL,
    UserName NVARCHAR(255) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    EmailVerified BIT NOT NULL,
    Gender TINYINT NULL,
    DOB DATETIME NULL,
    PAN NVARCHAR(20) NULL,
    Salt NVARCHAR(255) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(10) NULL,
    IPin BIGINT NOT NULL,
    PhoneVerified BIT NOT NULL,
    KYCVerified BIT NOT NULL,
    Address NVARCHAR(MAX) NULL,
    IsAdmin BIT NOT NULL,
    IsActive BIT NOT NULL,
    ProfilePicture NVARCHAR(MAX) NULL,
    LoginAttempts INT NOT NULL,
    GSTIN NVARCHAR(50) NULL,
    CompanyPAN NVARCHAR(20) NULL,
    CompanyTradeName NVARCHAR(255) NULL,
    CompanyLegalName NVARCHAR(255) NULL,
    BusinessCategory NVARCHAR(255) NULL,
    CompanyAddress NVARCHAR(MAX) NULL,
    CompanyLogo NVARCHAR(MAX) NULL,
    OutletId NVARCHAR(50) NULL,
    Prefix NVARCHAR(5) NULL,
    CreatedBy BIGINT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedBy BIGINT NULL,
    UpdatedAt DATETIME NULL
);
