CREATE TABLE TransactionLogs (
    Id BIGINT PRIMARY KEY IDENTITY(1,1),
    UserId BIGINT NOT NULL,
    RefUserId BIGINT NULL,
    ReferenceId NVARCHAR(MAX) NULL,
    Amount DECIMAL(18, 2) NULL,
    RemainingAmount DECIMAL(18, 2) NULL,
    AuditType TINYINT NULL,
    LogType TINYINT NULL,
    SurchargeType TINYINT NULL,
    CommissionType TINYINT NULL,
    Status TINYINT NOT NULL,
    MobileNumber NVARCHAR(15) NULL,
    Email NVARCHAR(50) NULL,
    Remark NVARCHAR(500) NULL,
    WalletUpdated BIT NOT NULL DEFAULT 0,
    EndPointIP NVARCHAR(100) NULL,
    Ipay_OrderId NVARCHAR(500) NULL,
    Ipay_StatusCode NVARCHAR(50) NULL,
    Ipay_ActCode NVARCHAR(50) NULL,
    Ipay_Uuid NVARCHAR(500) NULL,
    Ipay_Timestamp DATETIME NULL,
    Ipay_Environment NVARCHAR(50) NULL,
    Ipay_OutletId NVARCHAR(50) NULL,
    Ipay_Latitude NVARCHAR(50) NULL,
    Ipay_Longitude NVARCHAR(50) NULL,
    Ipay_Response NVARCHAR(MAX) NULL,
    CaptureType NVARCHAR(50) NULL,
    CreatedBy BIGINT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedBy BIGINT NULL,
    UpdatedAt DATETIME NULL,
    FOREIGN KEY (UserId) REFERENCES UserMasters(Id)
);
