CREATE TABLE Wallets (
    Id BIGINT PRIMARY KEY IDENTITY(1,1),
    UserId BIGINT NOT NULL,
    TotalBalance DECIMAL(18,2) NOT NULL,
    HeldAmount DECIMAL(18,2) NOT NULL,
    CreatedBy BIGINT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedBy BIGINT NULL,
    UpdatedAt DATETIME NULL,
    FOREIGN KEY (UserId) REFERENCES UserMasters(Id)
);